# Generated by Django 5.2 on 2025-04-29 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='foto',
            field=models.ImageField(default='fotos/default.jpg', upload_to='fotos'),
        ),
    ]
